
name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true


      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > docs/.vuepress/dist/.nojekyll

      # - name: Deploy GitHub Page Repo
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.MY_TOKEN }}
      #     external_repository: alist-repo/alist-repo.github.com
      #     publish_branch: gh-pages
      #     publish_dir: docs/.vuepress/dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.MY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/.vuepress/dist

